name=input("Enter Your Name:")
branch=input("Enter Your Branch:")
gender=input("What Is Your Gender:")
collegename=input("What's your college Name:")
age=input("Enter Your Age:")
print("NAME:",name)
print("BRANCH:",branch)
print("GENDER:",gender)
print("COLLEGE NAME:",collegename)
print("AGE:",age)
